### PR TITLE
Fixes for ISLANDORA-1613

### PR DESCRIPTION
**Pull request by bradspry**
Fixed ETDMS schema URL, per ISLANDORA-1613

### CODE REVIEW

**Comment by jordandukart** [comment]
This requires a `hook_update` as it's changing the database table in the install.

**Comment by bradspry** [comment]
@jordandukart 

I got this far, but it's not executing.  Tips?

```
**
 * Implements hook_update_N().
 *
 * Installs corrected ETDMS schema
 */
function islandora_oai_update_7102() {
db_update('islandora_oai_metadata_formats')
  ->fields(array(
    'oai2_schema' => 'http://www.ndltd.org/standards/metadata/etdms/1-0/etdms.xsd'
  ))
  ->condition('name', 'oai_etdms')
  ->condition('metadata_prefix', 'oai_etdms')
  ->execute();
}
```

**Comment by jordandukart** [comment]
When putting that in and running `drush updb` this ran fine for me @bradspry. Just to note you don't need to do `Implements hook_update_N().` just the description of what it's fixing.

**Comment by bradspry** [comment]
@jordandukart   Thank you for your help!   Committed the change, Travis is running now.

**Comment by bradspry** [comment]
@ruebot Yes Sir, my very first.

**Pull request merged**
