### PR TITLE
ISLANDORA-1341: add administer oai configuration permission

### PR DESCRIPTION
**Pull request by mark-cooper**

### CODE REVIEW

**Comment by DiegoPino** [comment]
@ruebot , i will do independent review at the end of the day, but at first look it's a very straight pull.

**Comment by DiegoPino** [comment]
@mark-cooper can you make a new pull request with your changes and correcting the constant use? This one is already closed. Or @jordandukart, do you wan't to fix it? Thanks ! :smile:

**Comment by mark-cooper** [comment]
@DiegoPino good catch. Will update soon, thx. :blush:

**Comment by DiegoPino** [comment]
@mark-cooper no problem! thank you

**Pull request merged**
