### PR TITLE
Allow PHP 5.3.3 to fail

### PR DESCRIPTION
**Pull request by whikloj**
**JIRA Ticket**: https://jira.duraspace.org/browse/ISLANDORA-2424

# What does this Pull Request do?

Allows PHP 5.3.3. to fail in Travis without marking the build as a failure.

# How should this be tested?

Travis will test

# Additional Notes:

* Does this change the interface, add a new feature, or otherwise change behaviours that would require updating documentation? no
* Does this change add any new dependencies? no
* Does this change require any other modifications to be made to the repository (ie. Regeneration activity, etc.)? no
* Could this change impact execution of existing code? no

# Interested parties

@Islandora/7-x-1-x-committers

### CODE REVIEW

**Comment by whikloj** [comment]
Had to fix a wide variety of things on this 🤞

**Comment by whikloj** [comment]
Bump 👊

**Review by DiegoPino — APPROVED** [review]
Approved!

**Comment by DiegoPino** [comment]
This has quite a few changes (thanks @whikloj) so won't rush on merging until Monday giving @Islandora/7-x-1-x-committers some time to review

**Comment by bondjimbond** [comment]
@DiegoPino I think we've had enough time for anyone to complain... Ready to merge?

**Pull request merged**
